import json
import os

from common.settings import BASE_DIR

# load config file
CONFIG_PATH = os.path.join(BASE_DIR, 'builder', 'config.json')
with open(CONFIG_PATH) as f:
    config = json.load(f)

NUMBER_ENTRIES_PER_SECTION = config['NUMBER_ENTRIES_PER_SECTION'] # NUMBER OF POINTS PER SECTIONS 
NUMBER_SECTIONS = config['NUMBER_SECTIONS'] # NUMBER OF SECTIONS TO BUILD REPORT

DBSCAN_NUMBER_SAMPLES_CLUSTER = config['DBSCAN']["NUMBER_SAMPLES_CLUSTER"]
DBSCAN_MAXIMUM_DISTANCE = config['DBSCAN']["MAXIMUM_DISTANCE"]
DBSCAN_PERCENTAGE_NOISE = config['DBSCAN']["PERCENTAGE_NOISE"]
